---

- hosts: all
  gather_facts: false
  
  tasks:
    - name: Ping host
      ping:

    - name: Some command 
      shell:
        cmd: uname -a
        chdir: /tmp   
        
    - name: Create invstack
      template:
        src: instackenv-template.json.j2
        dest: instackenv.json
        
